before:
  hooks:
    - go mod tidy
builds:
  - id: axwgameboy_windows
    main: ./cmd/axwgameboy
    goos:
      - windows
    goarch:
      - amd64
  - id: axwgameboy_linux
    main: ./cmd/axwgameboy
    goos:
      - linux
    goarch:
      - amd64
  - id: axwgameboy_android
    main: ./cmd/axwgameboy
    goos:
      - android
    goarch:
      - amd64
    gobinary: "gomobile"
    binary: "AXWGameboy.apk"
    ldflags:
      - \"-x main.version={{.Version}} -x main.commit={{.Commit}} -x main.date={{.Date}}\"
    flags:
      - -target=android
    hooks:
      pre:
        - mkdir -p {{dir .Path}}
        - go get golang.org/x/mobile/cmd/gomobile
        - gomobile init

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
    format: binary
    name_template: "{{ tolower .ProjectName }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
